config/routes.rb
Rails.application.routes.draw do
  resources :comidas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comida.rb
class Comida < ApplicationRecord
    self.per_page = 10 # numero de itens por pagina
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comidas_controller.rb
class ComidasController < ApplicationController
  before_action :set_comida, only: %i[ show edit update destroy ]

  # GET /comidas or /comidas.json
  def index
    @comidas = Comida.paginate(page: params[:page])
  end

  # GET /comidas/1 or /comidas/1.json
  def show
  end

  # GET /comidas/new
  def new
    @comida = Comida.new
  end

  # GET /comidas/1/edit
  def edit
  end

  # POST /comidas or /comidas.json
  def create
    @comida = Comida.new(comida_params)

    respond_to do |format|
      if @comida.save
        format.html { redirect_to comida_url(@comida), notice: "Comida was successfully created." }
        format.json { render :show, status: :created, location: @comida }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comidas/1 or /comidas/1.json
  def update
    respond_to do |format|
      if @comida.update(comida_params)
        format.html { redirect_to comida_url(@comida), notice: "Comida was successfully updated." }
        format.json { render :show, status: :ok, location: @comida }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comidas/1 or /comidas/1.json
  def destroy
    @comida.destroy

    respond_to do |format|
      format.html { redirect_to comidas_url, notice: "Comida was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comida
      @comida = Comida.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comida_params
      params.require(:comida).permit(:nome, :desc, :price, :quantidade, :estragado, :compra, :vencimento)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    if @post.save
        redirect_to @post, notice: "Post criado com sucesso"
    else
      render :new
    end

  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post, notice: "Post foi atualizado com sucesso"
    else
     render :edit
    end
  end

  def destroy
  end
  private
    def post_params
      params.require(:post).permit(:title,:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comidas_helper.rb
module ComidasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comidas/_comida.html.erb
<div id="<%= dom_id comida %>">
  <p>
    <strong>Nome:</strong>
    <%= comida.nome %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= comida.desc %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= comida.price %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= comida.quantidade %>
  </p>

  <p>
    <strong>Estragado:</strong>
    <%= comida.estragado %>
  </p>

  <p>
    <strong>Compra:</strong>
    <%= comida.compra %>
  </p>

  <p>
    <strong>Vencimento:</strong>
    <%= comida.vencimento %>
  </p>

</div>

app/views/comidas/_form.html.erb
<%= form_with(model: comida) do |form| %>
  <% if comida.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comida.errors.count, "error") %> prohibited this comida from being saved:</h2>

      <ul>
        <% comida.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :desc, style: "display: block" %>
    <%= form.text_area :desc %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.label :estragado, style: "display: block" %>
    <%= form.check_box :estragado %>
  </div>

  <div>
    <%= form.label :compra, style: "display: block" %>
    <%= form.date_field :compra %>
  </div>

  <div>
    <%= form.label :vencimento, style: "display: block" %>
    <%= form.datetime_field :vencimento %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comidas/edit.html.erb
<h1>Editing comida</h1>

<%= render "form", comida: @comida %>

<br>

<div>
  <%= link_to "Show this comida", @comida %> |
  <%= link_to "Back to comidas", comidas_path %>
</div>

app/views/comidas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comidas</h1>

<div id="comidas">
  <% @comidas.each do |comida| %>
    <%= render comida %>
    <p>
      <%= link_to "Show this comida", comida %>
    </p>
  <% end %>
</div>

<%= link_to "New comida", new_comida_path %>
<%= will_paginate @comidas %>

app/views/comidas/new.html.erb
<h1>New comida</h1>

<%= render "form", comida: @comida %>

<br>

<div>
  <%= link_to "Back to comidas", comidas_path %>
</div>

app/views/comidas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comida %>

<div>
  <%= link_to "Edit this comida", edit_comida_path(@comida) %> |
  <%= link_to "Back to comidas", comidas_path %>

  <%= button_to "Destroy this comida", @comida, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pagination</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/create.html.erb
<h1> Criando post</h1>
<%= form_with model: @post,data:{type: :hotwire} do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>
    <div>
    <%= form.submit %>
    </div>
<% end %>
<%= link_to "Voltar", posts_path %>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h1>Editando o <%= @post.id %>º post</h1>
<%= form_with model: @post,data:{type: :hotwire} do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>
    <div>
    <%= form.submit %>
    </div>
<% end %>
<%= link_to "Voltar", posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<%= link_to "criar um post", new_post_path%>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody data-target="post.row" data-action="click->posts#show">
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show',post %></td>
        <td><%= link_to 'Edit',edit_post_path(post) %></td>
        <td><%= button_to 'Delete',post,method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Vendo o <%= @post.id %>º post</h1>
<h2> <%= @post.title %> </h2>
<p> <%= @post.body %> </p>
<%= link_to 'Editar este post',edit_post_path(@post) %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>